name: Ganerate Podcast Feeds
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      - name: Run Feed Generator
        uses: frantizek/podcast-generator@main
